development:
  adapter: async
  url: redis://localhost:6379/1

test:
  adapter: async
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://redistogo:31f7bd1c4c396fd80373a0259fb419d3@greeneye.redistogo.com:10431/
